name: milo_family_assistant
description: "MILO – der KI-Familienhelfer"
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.15.0
  http: ^1.2.2
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
